/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ItemCard: typeof import('./src/components/ItemCard.vue')['default']
    Main: typeof import('./src/components/Main.vue')['default']
  }
}
